### ISSUE TITLE
Problem with installing dependencies - frontend

### ISSUE THREAD

**Issue by kamilniemczycki** [blumilksoftware/internships#47] opened 2021-07-19 11:42 UTC
The package installation instruction in the [readme.md](https://github.com/blumilksoftware/internships/blob/main/readme.md) file may be incorrect.

**I have an error in step 3.**
```
$> docker-compose exec node npm install
npm ERR! code EWORKSPACESCONFIG
npm ERR! workspaces config expects an Array

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-07-19T11_25_16_216Z-debug.log
```

The solution to this problem can be installation using the command: `docker-compose exec node yarn install`. From what I can see, only yarn handles ["workspaces"](https://github.com/blumilksoftware/internships/blob/e03e373f6f8975d5eabfe11a4680ecda4779965a/package.json#L58) as an object, npm requests workspaces as an array.
In addition, I would add commands to the readme file:
```
$> docker-compose exec node yarn build
$> docker-compose exec node yarn serve
```

P.S. WELL DONE!

**Comment by brzozka** [comment] 2021-07-20 07:20
Yes, this was caused by installing some tailwind typography dependency by Łukasz. It was already fixed but unfortunately on one of the biggest issues we have in this project, that's why it's not on main branch yet. It can be fixed as You say by using yarn or just removing workspace entry in package.json

**Comment by plencka** [comment] 2021-07-22 11:43
I think it should be fixed as of current version of main, @kamilniemczycki.
I need somebody else to verify. Current Readme seems fine.

**Comment by brzozka** [comment] 2021-07-22 12:32
Vue CLI created a git hook with eslint that lints the code on commit, because You probably don't have eslint it throws some errors. But I'm not sure tho.

**Comment by plencka** [comment] 2021-07-22 12:37
Well, either way... Random internet stranger won't be able to install project just with instructions, if they don't have all requirements installed on host machine. Either Readme needs to be updated, or requirements list for the project.

I'm personally not a fan of projects that throw you millions config-related errors which you need to look up on the web.

**Comment by brzozka** [comment] 2021-07-22 12:39
They won't be able to commit, not install.

**Comment by kamilniemczycki** [comment] 2021-07-22 18:36
> I think it should be fixed as of current version of main, @kamilniemczycki.
> I need somebody else to verify. Current Readme seems fine.

Yes, installing dependencies now works fine. 😊
Thanks!

**Closed** 2021-07-23 08:36 UTC
Labels: bug, frontend
